accumulate_grad_batches: 1
adam_epsilon: 1.0e-06
batch_size: 8
boost_factor: 1.5
civi_code_path: data/parsed_civil_code/en_civil_code.json
ckpt_steps: 1000
clauses_db_path: data\ir_dataset\clauses_database.csv
data_dir: data\COLIEE2025statute_data-English\data_en_topk_150_r02_r03
dense_weight: 0.7
dropout: 0.1
file_output_id: clauseRetrieval
final_div_factor: 10000.0
gpus:
- 0
ignore_index: -100
log_dir: settings\clause_retrieval_gpu
lr: 2.0e-05
lr_scheduler: onecycle
main_enss_path: settings/bert-base-japanese-whole-word-masking_5ckpt_150-newE5Seq512L2e-5/datout/test_{}_5_80_0015.txt
max_epochs: 5
max_keep_ckpt: 1
max_seq_length: 256
model_name_or_path: bert-base-uncased
no_dev: false
no_test: false
no_train: false
optimizer: adam
pretrained_checkpoint: null
retrieval_top_k: 100
use_clause_retrieval: true
warmup_steps: 0
weight_decay: 0.0001
